name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      separated-pkgs: ${{ steps.separate.outputs.out }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - id: separate
        run: echo "out=$(perl separate-test-pkg.pl)" >> $GITHUB_OUTPUT
  test:
    name: Test (${{ matrix.target.name }})
    needs:
      - prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.prepare.outputs.separated-pkgs) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go test -v ${{ join(matrix.target.packages, ' ') }}
